version: '3.7'

networks:
    default:
        name: krakend-impl-network

services:
    krakend:
        container_name: krakend
        image: devopsfaith/krakend:2.5
        volumes:
            - ./config:/etc/krakend
        ports:
            - '5000:5000'
            - '8090:8090'

    kraken_designer:
        image: krakend/designer:2.4
        container_name: krakend_designer
        ports:
            - '8787:80'

    hello-service:
        build: ./hello-service
        image: krakend-hello-service:v1
        restart: always
        hostname: hello-service
        ports:
            - 4000:4000

    user-service:
        build: ./user-service
        image: krakend-user-service:v1
        restart: always
        hostname: user-service
        ports:
            - 4001:4001
